var FilterConstants = {
  SEARCHMAPMOVED: "SEARCHMAPMOVED",
  UPDATECHECKIN: "UPDATECHECKIN",
  UPDATECHECKOUT: "UPDATECHECKOUT",
  UPDATEGUESTS: "UPDATEGUESTS",
  UPDATEDATES: "UPDATEDATES",
  RESETDATES: "RESETDATES"
}

module.exports = FilterConstants;
